### ISSUE TITLE
it's the only way that i found to contact you

### ISSUE THREAD

**Issue by xhottam** [KurtE/Phantom_Phoenix#2]
Hi KurtE,

 I hope you are well.  
 Sorry, to contact you opening  an incident  but it's  the only way that i have found.

 it's about the below thread.
http://forums.trossenrobotics.com/showthread.php?7779-How-to-build-and-download-firmware-to-Arbotix-Pro

 Quick questions. were you able to reprogram the arbotix-pro ?. Base on the first picture in the thread i cannot able to do it, don't even recognize the board. I'm using a stlink v2 and olimex adapter.
 Could you, please, share your connection settings and the stuff that you did to connect through SWD? 
 
 Thanks in advance.

**Comment by KurtE** [comment]
Actually there are a few different ways to contact…

You could have responded to the thread you linked to,  and likewise you could have sent a PM…

 

Sorry, I have not touched an Arbotix Pro in probably well over a year. 

 

Yes I was able to reprogram it.  Again assuming you had a latter arbotix Pro that had a proper connector setup and not the original ones with the HROS1, which you in theory needed to build a rig in order to program.

 

My only notes on this is what you see in that thread.  In particular #5 from tician to set the software to use SWD and not JTAG and the markings on the board were wrong for what is pin 1.

 

Sorry again I have not done it in a long while as I prefer to use other boards.
